### ISSUE TITLE
Credential selection modifies 'instanceUrl' parameter, causing subsequent commands to fail with 'Only absolute URLs are supported' error

### ISSUE THREAD

**Issue by sfnmro** [micheletriaca/fast-sfdc#45]
### Steps to reproduce
- Switch between stored Salesforce credentials
- Execute any command (e.g. retrieve or deploy)

### Expected behavior
Subsequent commands should execute without error, regardless of credential switching.

### Actual behavior
After switching Salesforce credentials, the `instanceUrl` parameter of the selected credential in **_fastsfdc.json_** gets replaced with a non-absolute URL, causing any subsequent command to break with the following error message: **_"Something went wrong. Only absolute URLs are supported."_**

### Workaround
Manually edit the **_fastsfdc.json_** file to include the **_"https://"_** prefix in the `instanceUrl` parameter of the selected credential.

### Environment
Operating System: macOS 13.0 (22A380)
Fastsfdc Version: 1.13

**Comment by micheletriaca** [comment]
Thank @sfnmro 🤝
